/** Authored alternatives for the elementary short-answer bank. They are
 * hypotheses to compare, never automatic diagnoses of a misconception. */
export const alternatives: Record<string, string[]> = Object.fromEntries(
  [
    ["plentiful", "scarce", "spoiled"],
    ["sock", "moon", "cat"],
    ["cake", "cat", "cap"],
    ["re", "un", "pre"],
    ["not", "again", "before"],
    ["life", "earth", "water"],
    ["a dog playing", "a dog sleeping", "a dog eating"],
    ["pollination", "rain", "nest building"],
    ["trees are helpful", "all trees are tall", "trees only provide shade"],
    ["transport choices", "building houses", "closing all roads"],
    ["benefits of wetlands", "ocean depth", "types of desert plants"],
    ["blue", "red", "green"],
    ["twigs", "seeds", "leaves"],
    ["nine", "five", "noon"],
    ["the plant in sunlight", "the shaded plant", "both plants equally"],
    ["raining", "sunny", "snowing"],
    ["tired", "hungry", "excited"],
    ["rain", "a long dry spell", "a hot wind drying the ground"],
    ["anxious", "asleep", "relaxed"],
    ["connection", "the number of people alone", "the width of the street"],
    ["wash hands", "eat", "clear the plates"],
    ["water it", "watch it sprout", "collect its fruit"],
    ["bake", "mix", "serve"],
    ["problem-solution", "time order only", "comparison only"],
    ["cause and effect", "compare and contrast", "a list without connections"],
    ["small", "loud", "heavy"],
    ["dry", "wet", "icy"],
    ["not wide", "very steep", "very long"],
    ["short", "angry", "detailed"],
    ["persuasive", "hidden", "uncertain"],
    ["Birds", "sing"],
    ["runs", "child", "The"],
    ["bright", "moon", "shines"],
    ["slowly", "She", "walked"],
    ["a bridge", "They", "built"],
    ["question mark", "full stop", "exclamation mark"],
    ["The dog barked", "Because the dog", "The noisy dog"],
    ["commas", "question marks", "apostrophes"],
    ["quotation marks", "brackets", "apostrophes"],
    ["a semicolon", "an apostrophe", "a question mark"],
    ["One cat runs", "One cat run", "One cat running"],
    ["walked", "walking", "will walk"],
    ["They are ready", "They is ready", "They am ready"],
    ["has finished", "will finish", "is finishing"],
    ["She opened and read", "She opened and reads", "She opens and read"],
    ["characters and setting", "a shopping list", "the page number"],
    ["a problem", "a page number", "the book's price"],
    ["resolution", "opening", "setting"],
    ["thoughts and feelings", "only spelling", "only the number of pages"],
    ["a relevant scene", "an unrelated detail", "a repeated title"],
    ["in order", "mixed up", "with the final step first"],
    ["Use a toothbrush", "Clouds are white", "The park is nearby"],
    ["topic sentence", "an unrelated closing sentence", "the page number"],
    ["a relevant example", "an unrelated opinion", "repeating the title"],
    ["clear transitions", "disconnected facts", "removing the sequence"],
    ["an opinion", "a fact", "a question"],
    ["It has swings", "My shoe is blue", "Tomorrow is Tuesday"],
    ["evidence", "a repeated claim", "an unrelated detail"],
    ["revise the claim", "hide the evidence", "repeat the claim more loudly"],
    ["Text B", "Text A", "both texts"],
    ["opposite directions", "the same direction", "neither level changes"],
    ["after lunch", "after we", "after went"],
    ["urgency", "boredom", "uncertainty"],
    ["asking", "telling", "giving a command"],
    ["full", "quiet", "empty"],
    ["happy", "cold", "worried"],
    ["a young plant", "a stone", "a fully grown tree"],
    ["a growing tree", "a plastic cup", "a wooden chair"],
    ["thick stems", "thin unprotected leaves", "wide open pores all day"],
    [
      "passed from parents",
      "chosen each morning",
      "always learned from friends",
    ],
    ["air and water", "eating soil", "sunlight alone as matter"],
    ["food", "its predator", "a decomposer"],
    ["a pond", "a dry cupboard", "a dry sand dune"],
    ["grass", "fox", "another rabbit"],
    ["decomposers", "sunlight alone", "rocks alone"],
    ["hearing", "sight", "smell"],
    ["heart", "lungs", "stomach"],
    ["lungs", "stomach", "bones"],
    ["circulatory system", "digestive system", "skeletal system"],
    ["solid", "liquid", "gas"],
    ["water", "nothing because it disappears", "a different substance"],
    ["gravity", "friction", "magnetism"],
    ["potential", "kinetic", "sound"],
    ["a thermometer", "a ruler", "a rain gauge"],
    ["a long-term pattern", "one afternoon's weather", "one day's forecast"],
    ["erosion", "deposition", "weathering"],
    ["in the day", "only at night", "only at midnight"],
    [
      "reflect sunlight",
      "make its own visible light",
      "reflect Earth's shadow",
    ],
    ["an observation", "a wish", "a prediction"],
    ["legend", "title", "scale"],
    ["south", "east", "west"],
    ["firefighters", "librarians", "postal workers"],
    ["legislative", "executive", "judicial"],
    [
      "separation of powers",
      "hereditary succession",
      "power held by one branch",
    ],
    ["2001", "2010"],
    ["a need", "a want"],
    ["opportunity cost", "total income", "the selected choice"],
    ["a good", "a service"],
    ["triangle", "rectangle", "pentagon"],
    ["rectangle", "triangle", "pentagon"],
    ["pentagon", "triangle", "rectangle"],
    ["apple", "feather", "equal masses"],
    ["acute", "right", "obtuse"],
    ["right", "acute", "obtuse"],
    ["obtuse", "acute", "right"],
  ].map(([answer, ...wrong]) => [answer, wrong]),
);

/** Full claims for binary tasks. Both sides use comparable wording/length. */
export const binaryClaims: [string, string, string][] = [
  [
    "opinion paragraph",
    "An opinion paragraph should include supporting reasons.",
    "An opinion paragraph does not need supporting reasons.",
  ],
  [
    "plant need water",
    "A plant needs water to grow.",
    "A plant can grow without any water.",
  ],
  [
    "food source becomes scarce",
    "Less food can change an animal population.",
    "Less food cannot change an animal population.",
  ],
  [
    "bones and muscles",
    "Bones and muscles work together to move us.",
    "Bones move the body without muscles working.",
  ],
  [
    "liquid water take",
    "Liquid water takes the shape of its container.",
    "Liquid water keeps a fixed shape in every container.",
  ],
  [
    "total mass stay",
    "The total mass stays the same in the closed container.",
    "Some mass disappears when the salt dissolves.",
  ],
  [
    "pushing a toy",
    "Pushing the car applies a force to it.",
    "Pushing the car does not apply a force.",
  ],
  [
    "pull act toward",
    "A pull acts toward the person pulling.",
    "A pull acts away from the person pulling.",
  ],
  [
    "friction slow",
    "Friction can slow down a sliding object.",
    "Friction cannot slow down a sliding object.",
  ],
  [
    "balanced forces",
    "Balanced forces can leave an object at rest.",
    "Balanced forces must make a resting object move.",
  ],
  [
    "lamp need",
    "A lamp needs an energy source to shine.",
    "A lamp can shine without an energy source.",
  ],
  [
    "sunlight warm",
    "Sunlight can warm a dark surface.",
    "Sunlight cannot warm a dark surface.",
  ],
  [
    "moving ball",
    "A moving ball has energy of motion.",
    "A moving ball has no energy of motion.",
  ],
  [
    "transfer as heat",
    "Friction can transfer energy as heat.",
    "Energy disappears when friction stops an object.",
  ],
  [
    "rain a kind",
    "Rain is one kind of precipitation.",
    "Rain is not a kind of precipitation.",
  ],
  [
    "weather data",
    "Weather records over time can show patterns.",
    "Weather records over time cannot show patterns.",
  ],
  [
    "sun a major",
    "The Sun supplies energy for the water cycle.",
    "The Sun supplies no energy for the water cycle.",
  ],
  [
    "sand an earth",
    "Sand is one of Earth's natural materials.",
    "Sand is not an Earth material.",
  ],
  [
    "flowing water",
    "Flowing water can carry soil away.",
    "Flowing water cannot move soil.",
  ],
  [
    "deposition drop",
    "Deposition leaves transported sediment in a new place.",
    "Deposition breaks rock down without moving or leaving sediment.",
  ],
  [
    "atmosphere, water",
    "Air, water, and land can affect one another.",
    "Air, water, and land cannot affect one another.",
  ],
  [
    "earth rotate",
    "Earth's rotation produces day and night.",
    "Earth's rotation does not produce day and night.",
  ],
  [
    "earth travel",
    "Earth travels around the Sun.",
    "Earth does not travel around the Sun.",
  ],
  [
    "stars appear",
    "Great distances can make stars appear faint.",
    "A star's distance cannot affect how bright it looks.",
  ],
  [
    "prediction a statement",
    "A prediction describes what may happen.",
    "A prediction only describes what already happened.",
  ],
  [
    "fair test",
    "Change one chosen factor in a fair test.",
    "Change every factor together in a fair test.",
  ],
  [
    "repeating a trial",
    "Repeating trials can help check reliability.",
    "Repeating trials cannot help check reliability.",
  ],
  [
    "map show",
    "A map can use symbols to show places.",
    "A map cannot use symbols to show places.",
  ],
  [
    "latitude lines",
    "Latitude measures position north or south of the equator.",
    "Latitude measures position east or west of the prime meridian.",
  ],
  [
    "places to live",
    "People need places where they can live.",
    "Places to live are not a human need.",
  ],
  [
    "weather affect",
    "Weather can affect what people wear.",
    "Weather cannot affect what people wear.",
  ],
  [
    "river influence",
    "A river can influence where a community develops.",
    "A river cannot influence where a community develops.",
  ],
  [
    "building roads",
    "Building roads can change a natural environment.",
    "Building roads cannot change a natural environment.",
  ],
  [
    "conserving water",
    "Saving water can help communities in dry regions.",
    "Saving water cannot help communities in dry regions.",
  ],
  [
    "neighbours cooperate",
    "Cleaning a shared park can involve cooperation.",
    "Cleaning a shared park cannot involve cooperation.",
  ],
  [
    "public library",
    "A public library is a community resource.",
    "A public library is not a community resource.",
  ],
  [
    "communities solve",
    "Discussion and shared action can help solve community problems.",
    "Discussion and shared action cannot help solve community problems.",
  ],
  [
    "different priorities",
    "Groups can have different priorities for one project.",
    "Every group must have the same priorities for one project.",
  ],
  [
    "classroom rules",
    "Classroom rules can help people learn safely.",
    "Classroom rules cannot help people learn safely.",
  ],
  [
    "taking turns",
    "Taking turns can be a way to act fairly.",
    "Taking turns cannot be a way to act fairly.",
  ],
  [
    "having a right",
    "Having rights also involves respecting other people's rights.",
    "Having rights means ignoring other people's rights.",
  ],
  [
    "fair rule",
    "A fair rule should apply consistently.",
    "A fair rule should change depending on who breaks it.",
  ],
  [
    "changing a rule",
    "A community can discuss changing an unfair rule.",
    "A community cannot discuss changing an unfair rule.",
  ],
  [
    "class vote",
    "A class vote can help choose among shared options.",
    "A class vote cannot help choose among shared options.",
  ],
  [
    "local government",
    "Local government can help maintain public roads.",
    "Local government cannot help maintain public roads.",
  ],
  [
    "laws rules",
    "Laws are rules made through government processes.",
    "Laws are only personal wishes, outside government processes.",
  ],
  [
    "yesterday",
    "Yesterday comes before today.",
    "Yesterday comes after today.",
  ],
  [
    "chronological order",
    "Timelines put events in chronological order.",
    "Timelines put events in order of importance instead of time.",
  ],
  [
    "overlap in time",
    "Different events on a timeline can overlap.",
    "Different events on a timeline can never overlap.",
  ],
  [
    "being earlier",
    "An earlier date alone proves that one event caused another.",
    "An earlier date alone does not prove that one event caused another.",
  ],
  [
    "old photograph",
    "An old photograph can give clues about the past.",
    "An old photograph cannot give clues about the past.",
  ],
  [
    "diary written",
    "A diary written at the time is a firsthand source.",
    "A diary written at the time is not a firsthand source.",
  ],
  [
    "two people describe",
    "Two people can describe the same event differently.",
    "Two people must describe the same event identically.",
  ],
  [
    "source’s perspective",
    "A source's perspective affects how we interpret it.",
    "A source's perspective has no effect on interpretation.",
  ],
  [
    "families have",
    "Families can have different traditions.",
    "Every family must have the same traditions.",
  ],
  [
    "listening respectfully",
    "Listening respectfully helps us learn about traditions.",
    "Listening respectfully does not help us learn about traditions.",
  ],
  [
    "music, language",
    "Music, language, and food can express culture.",
    "Music, language, and food cannot express culture.",
  ],
  [
    "cultures change",
    "Contact and migration can change cultures.",
    "Contact and migration cannot change cultures.",
  ],
  [
    "one person’s experience",
    "One person's experience represents every member of a culture.",
    "One person's experience does not represent every member of a culture.",
  ],
  [
    "money is limited",
    "Limited money means people must make choices.",
    "Limited money means people can afford every choice.",
  ],
  [
    "budget help",
    "A budget can help plan how to use money.",
    "A budget cannot help plan how to use money.",
  ],
  [
    "weigh costs",
    "People can compare costs and benefits before deciding.",
    "People cannot compare costs and benefits before deciding.",
  ],
  [
    "haircut",
    "A haircut is a service someone provides.",
    "A haircut is a physical good someone makes.",
  ],
  [
    "producer make",
    "A producer makes goods or provides services.",
    "A producer only buys goods and never provides anything.",
  ],
  [
    "trade let",
    "Trade can supply things a community does not produce.",
    "Trade can only supply things a community already produces.",
  ],
  [
    "specialization",
    "Specialized communities can depend on one another.",
    "Specialized communities never depend on one another.",
  ],
  [
    "balance is level",
    "The two stones on the level balance have equal mass.",
    "The two stones on the level balance have different masses.",
  ],
  [
    "both describe travelling",
    "Both texts describe a journey to school.",
    "Only one text describes a journey to school.",
  ],
  [
    "square have four right",
    "Every square has four right angles.",
    "Some squares do not have four right angles.",
  ],
  [
    "rectangle have four equal",
    "Every rectangle has four equal sides.",
    "A rectangle can have two different side lengths.",
  ],
  [
    "three pairs",
    "A quadrilateral can have three pairs of opposite parallel sides.",
    "A quadrilateral has only two pairs of opposite sides.",
  ],
  [
    "square also a rectangle",
    "Every square also meets the definition of a rectangle.",
    "A square never meets the definition of a rectangle.",
  ],
  [
    "rectangle also a square",
    "Every rectangle also meets the definition of a square.",
    "Some rectangles have unequal adjacent sides, so they are not squares.",
  ],
  [
    "triangle have two",
    "A triangle can contain two right angles.",
    "A triangle cannot contain two right angles.",
  ],
];
