PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, name TEXT NOT NULL, password_hash TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS auth_sessions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS auth_user ON auth_sessions(user_id);
CREATE TABLE IF NOT EXISTS rate_limits (key TEXT PRIMARY KEY, count INTEGER NOT NULL, resets_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS children (id TEXT PRIMARY KEY, parent_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, nickname TEXT NOT NULL, age INTEGER NOT NULL CHECK(age BETWEEN 7 AND 11), grade INTEGER NOT NULL CHECK(grade BETWEEN 1 AND 6), goal TEXT NOT NULL, diagnostic_complete INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS children_parent ON children(parent_id);
CREATE TABLE IF NOT EXISTS concepts (id TEXT PRIMARY KEY, name TEXT NOT NULL, domain TEXT NOT NULL, data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS concept_prerequisites (concept_id TEXT NOT NULL REFERENCES concepts(id), prerequisite_id TEXT NOT NULL REFERENCES concepts(id), PRIMARY KEY(concept_id,prerequisite_id));
CREATE TABLE IF NOT EXISTS misconceptions (id TEXT PRIMARY KEY, data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS concept_misconceptions (concept_id TEXT NOT NULL REFERENCES concepts(id), misconception_id TEXT NOT NULL REFERENCES misconceptions(id), PRIMARY KEY(concept_id,misconception_id));
CREATE TABLE IF NOT EXISTS teaching_strategies (id TEXT PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS learner_concept_states (child_id TEXT NOT NULL REFERENCES children(id) ON DELETE CASCADE, concept_id TEXT NOT NULL REFERENCES concepts(id), data TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY(child_id,concept_id));
CREATE TABLE IF NOT EXISTS learner_misconception_states (child_id TEXT NOT NULL REFERENCES children(id) ON DELETE CASCADE, misconception_id TEXT NOT NULL REFERENCES misconceptions(id), data TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY(child_id,misconception_id));
CREATE TABLE IF NOT EXISTS teaching_strategy_evidence (child_id TEXT NOT NULL REFERENCES children(id) ON DELETE CASCADE, strategy_id TEXT NOT NULL REFERENCES teaching_strategies(id), domain TEXT NOT NULL, data TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY(child_id,strategy_id,domain));
CREATE TABLE IF NOT EXISTS learning_sessions (id TEXT PRIMARY KEY, child_id TEXT NOT NULL REFERENCES children(id) ON DELETE CASCADE, state TEXT NOT NULL, data TEXT NOT NULL, created_at TEXT NOT NULL, completed_at TEXT);
CREATE INDEX IF NOT EXISTS sessions_child ON learning_sessions(child_id,created_at);
CREATE UNIQUE INDEX IF NOT EXISTS one_active_session ON learning_sessions(child_id) WHERE completed_at IS NULL;
CREATE TABLE IF NOT EXISTS lesson_plans (session_id TEXT PRIMARY KEY REFERENCES learning_sessions(id) ON DELETE CASCADE, data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS session_events (id TEXT PRIMARY KEY, session_id TEXT NOT NULL REFERENCES learning_sessions(id) ON DELETE CASCADE, child_id TEXT NOT NULL REFERENCES children(id) ON DELETE CASCADE, type TEXT NOT NULL, metadata TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS events_session ON session_events(session_id,created_at);
CREATE TABLE IF NOT EXISTS practice_attempts (id TEXT PRIMARY KEY, session_id TEXT NOT NULL REFERENCES learning_sessions(id) ON DELETE CASCADE, child_id TEXT NOT NULL REFERENCES children(id) ON DELETE CASCADE, concept_id TEXT NOT NULL REFERENCES concepts(id), question_id TEXT NOT NULL, correct INTEGER NOT NULL, assistance INTEGER NOT NULL, strategy_id TEXT NOT NULL REFERENCES teaching_strategies(id), outcome TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS homework_uploads (id TEXT PRIMARY KEY, child_id TEXT NOT NULL REFERENCES children(id) ON DELETE CASCADE, mime TEXT NOT NULL, image BLOB NOT NULL, concept_id TEXT REFERENCES concepts(id), created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS homework_child ON homework_uploads(child_id);
CREATE TABLE IF NOT EXISTS product_events (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, type TEXT NOT NULL, metadata TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS product_user ON product_events(user_id,created_at);
