import type { SkillContent } from "./schema";

// Original micro-passages: no copied textbook or comparator content.
type Case = [
  passage: string,
  question: string,
  answer: string,
  distractor: string,
  reason: string,
];
interface Scope {
  grade: number;
  slug: string;
  name: string;
  strand: string;
  code: string;
  hint: string;
  cases: Case[];
}
const scopes: Scope[] = [
  {
    grade: 6,
    slug: "evidence",
    name: "Citing evidence for an inference",
    strand: "Reading literature",
    code: "RL.6.1",
    hint: "Separate what the passage states from what those details suggest.",
    cases: [
      [
        "Lena checked the clock three times and kept her coat on beside the door.",
        "Which inference is supported?",
        "Lena is waiting to leave",
        "Lena has lost her coat",
        "Repeated clock-checking and keeping a coat on support readiness to leave.",
      ],
      [
        "When the puppy limped, Omar stopped the game and carried it home.",
        "Which detail supports the inference that Omar is caring?",
        "He carried the injured puppy home",
        "He was playing a game",
        "His response to the injury is evidence of care.",
      ],
      [
        "Mira erased her answer, checked the example, and tried the problem again.",
        "Which inference is best supported?",
        "Mira is willing to revise her work",
        "Mira has finished every problem",
        "Checking and retrying demonstrate persistence, not completion of all work.",
      ],
    ],
  },
  {
    grade: 6,
    slug: "central_idea",
    name: "Central idea and supporting details",
    strand: "Reading informational text",
    code: "RI.6.2",
    hint: "Choose the idea broad enough to connect the details, without adding unsupported claims.",
    cases: [
      [
        "Trees shade streets, absorb rainwater, and provide nesting places for birds.",
        "What is the central idea?",
        "Trees benefit urban environments in several ways",
        "Trees only benefit birds",
        "All three details describe different urban benefits.",
      ],
      [
        "The library lends tools, hosts language classes, and provides internet access.",
        "Which summary covers the passage?",
        "The library offers services beyond lending books",
        "The library no longer has books",
        "The services support the broader summary; the text never says books were removed.",
      ],
      [
        "Cycling replaces some car trips, reduces fuel use, and can lower traffic noise.",
        "Which claim is supported by all the details?",
        "Cycling can reduce impacts of car travel",
        "Cycling eliminates every kind of pollution",
        "The qualified claim connects the effects without overgeneralizing.",
      ],
    ],
  },
  {
    grade: 6,
    slug: "context",
    name: "Meaning from context",
    strand: "Language",
    code: "L.6.4",
    hint: "Use the surrounding actions or contrasts to test a possible meaning.",
    cases: [
      [
        "The once murky water became clear after the filter removed the mud.",
        "What does murky mean here?",
        "Cloudy or difficult to see through",
        "Very hot",
        "The contrast with clear water and the mention of mud support cloudy.",
      ],
      [
        "Unlike his noisy friends, Ben was reserved and spoke only when asked.",
        "What does reserved mean here?",
        "Quiet and restrained",
        "Already booked",
        "The context describes behavior, not a reservation.",
      ],
      [
        "The fragile shell cracked under a slight touch.",
        "What does fragile mean?",
        "Easily broken",
        "Extremely heavy",
        "Cracking under a slight touch shows low resistance to damage.",
      ],
    ],
  },
  {
    grade: 6,
    slug: "claims",
    name: "Claims and relevant evidence",
    strand: "Argument writing",
    code: "W.6.1",
    hint: "Evidence must bear on the specific claim, not merely mention the same topic.",
    cases: [
      [
        "Claim: A later bus would help students attend clubs. Survey: 28 club members miss activities because the only bus leaves early.",
        "Does the survey support the claim?",
        "Yes, it identifies a transport barrier",
        "No, it only describes bus color",
        "The survey connects early departure to missed clubs.",
      ],
      [
        "Claim: The new lamps reduce electricity use. The lamps are painted blue.",
        "How relevant is this evidence?",
        "It does not measure electricity use",
        "It proves the lamps save power",
        "Color alone does not establish energy consumption.",
      ],
      [
        "Claim: The garden needs more water. Soil moisture measurements stayed low for a week.",
        "Which addition would strengthen the argument?",
        "Compare measurements with the plants' moisture needs",
        "Describe the gardener's favorite music",
        "A relevant benchmark connects the measurement to the claim.",
      ],
    ],
  },
  {
    grade: 7,
    slug: "theme",
    name: "Developing a theme",
    strand: "Reading literature",
    code: "RL.7.2",
    hint: "A theme is an idea developed by events, not merely the topic or a plot detail.",
    cases: [
      [
        "A runner trained alone, rejected advice, then improved after listening to teammates.",
        "Which theme is supported?",
        "Accepting help can support growth",
        "Winning is the only purpose of friendship",
        "Improvement follows accepting others' advice.",
      ],
      [
        "After several failed designs, Jo tested each weakness and finally built a working bridge.",
        "Which theme fits?",
        "Learning from failure can lead to progress",
        "Good designs never fail",
        "Repeated revision links failure to learning.",
      ],
      [
        "A child returned a lost wallet even though no one was watching.",
        "Which theme fits the action?",
        "Integrity does not depend on an audience",
        "Honesty matters only when rewarded",
        "The choice is honest despite no visible observer.",
      ],
    ],
  },
  {
    grade: 7,
    slug: "structure",
    name: "Informational text structure",
    strand: "Reading informational text",
    code: "RI.7.5",
    hint: "Ask how ideas are connected: sequence, comparison, cause, or problem and response.",
    cases: [
      [
        "First rinse the seeds. Next place them on damp paper. Finally check them each day.",
        "Which structure organizes the passage?",
        "Sequence",
        "Compare and contrast",
        "The directions are arranged in time order.",
      ],
      [
        "The footbridge flooded every spring, so engineers raised its deck.",
        "Which structure is most evident?",
        "Problem and solution",
        "Unrelated list",
        "Flooding is the problem and raising the deck responds to it.",
      ],
      [
        "Both bikes have gears, but one folds for storage while the other has a fixed frame.",
        "Which structure is used?",
        "Compare and contrast",
        "Chronological biography",
        "The passage states a similarity and a difference.",
      ],
    ],
  },
  {
    grade: 7,
    slug: "argument",
    name: "Evaluating reasons and evidence",
    strand: "Reading informational text",
    code: "RI.7.8",
    hint: "Check whether the evidence supports the conclusion and whether an absolute claim goes too far.",
    cases: [
      [
        "Two students enjoyed the app, so the author claims every student will learn faster with it.",
        "What is the weakness?",
        "A small sample cannot justify the universal claim",
        "Enjoyment proves learning speed",
        "Two opinions cannot establish an outcome for every student.",
      ],
      [
        "A report compares electricity bills before and after insulation, noting a warmer winter afterward.",
        "What should a reader consider?",
        "Weather may also explain lower energy use",
        "Insulation can never affect energy use",
        "The changed weather is an alternative explanation.",
      ],
      [
        "A writer argues a road is unsafe using crash records and measured vehicle speeds.",
        "Why is this evidence relevant?",
        "It directly concerns traffic risk",
        "All numerical evidence proves any claim",
        "The measurements relate to the specific safety claim.",
      ],
    ],
  },
  {
    grade: 7,
    slug: "revision",
    name: "Revising for precision",
    strand: "Writing",
    code: "W.7.5",
    hint: "Prefer a revision that clarifies the claim without exaggeration or unnecessary words.",
    cases: [
      [
        "Draft: The experiment was good and stuff happened.",
        "Which revision is more precise?",
        "The warmed sample dissolved in 40 seconds",
        "The experiment was super good",
        "A measured observation replaces vague evaluation.",
      ],
      [
        "Draft: Everyone always agrees that uniforms are perfect.",
        "Which revision is more defensible?",
        "Some students say uniforms simplify clothing choices",
        "Uniforms are completely perfect for everyone",
        "The revision qualifies the group and states a specific benefit.",
      ],
      [
        "Draft: The river was polluted. This caused a problem.",
        "Which revision clarifies the effect?",
        "Pollution reduced oxygen levels and harmed fish",
        "The river problem was problematic",
        "The revision names a mechanism and consequence.",
      ],
    ],
  },
  {
    grade: 8,
    slug: "character",
    name: "Analyzing character decisions",
    strand: "Reading literature",
    code: "RL.8.3",
    hint: "Connect a decision to its stated motive and its effect on later events.",
    cases: [
      [
        "Afraid of disappointing her team, Noor hid the broken sensor. The unnoticed fault ruined the next trial.",
        "How does the decision advance the plot?",
        "Concealing the fault leads to a failed trial",
        "Reporting the fault saves the trial",
        "The failure follows the choice to conceal the problem.",
      ],
      [
        "Eli expected rejection but shared his poem. His classmates asked to hear more.",
        "What contrast develops the character?",
        "His fearful expectation contrasts with a welcoming response",
        "His confidence proves he never worried",
        "The response challenges his expectation.",
      ],
      [
        "After watching her neighbor repair bicycles for free, Ana opened a weekend repair stand.",
        "What motivates Ana's action?",
        "The neighbor's example of service",
        "A stated promise of prize money",
        "The text names the model she observed, not a financial reward.",
      ],
    ],
  },
  {
    grade: 8,
    slug: "conflicting_sources",
    name: "Comparing conflicting accounts",
    strand: "Reading informational text",
    code: "RI.8.9",
    hint: "Identify exactly where sources disagree before judging their evidence.",
    cases: [
      [
        "Report A says the park opened in May, citing council records. Report B says June, citing one visitor's memory.",
        "Which source offers stronger evidence for the opening date?",
        "Report A's contemporary records",
        "Report B solely because it is shorter",
        "Records tied to the event generally support the date better than one later recollection.",
      ],
      [
        "One article says attendance rose 10%; another says ticket revenue fell 5%.",
        "Must these claims conflict?",
        "No, attendance and revenue measure different things",
        "Yes, more attendees always means more revenue",
        "Prices or discounts can change revenue independently of attendance.",
      ],
      [
        "Two surveys report different preferences but sample different age groups.",
        "What should be compared first?",
        "Who was surveyed and how the samples were selected",
        "Which report has a brighter cover",
        "Sampling differences can explain different results.",
      ],
    ],
  },
  {
    grade: 8,
    slug: "counterclaims",
    name: "Addressing counterclaims",
    strand: "Argument writing",
    code: "W.8.1",
    hint: "A useful response fairly states the opposing concern and answers it with evidence or a tradeoff.",
    cases: [
      [
        "Proposal: Add a school garden. Concern: Summer maintenance will be difficult.",
        "Which response addresses the concern?",
        "Arrange a documented volunteer watering schedule",
        "Say gardening is obviously good",
        "A maintenance plan responds to the specific obstacle.",
      ],
      [
        "Claim: Extend library hours. Counterclaim: Staffing costs would increase.",
        "Which evidence is most useful?",
        "A budget comparing added costs with available funding",
        "A list of book cover colors",
        "The budget directly tests the cost concern.",
      ],
      [
        "A writer describes opponents as lazy instead of discussing their argument.",
        "What revision improves the response?",
        "State their actual reason and answer it with evidence",
        "Add a stronger insult",
        "Addressing the claim is more relevant than attacking people.",
      ],
    ],
  },
  {
    grade: 8,
    slug: "voice",
    name: "Active and passive voice",
    strand: "Language",
    code: "L.8.1",
    hint: "In active voice the subject performs the action; in passive voice it receives the action.",
    cases: [
      [
        "The samples were labeled by the researcher.",
        "Which revision uses active voice?",
        "The researcher labeled the samples",
        "The samples were carefully labeled",
        "The researcher becomes the subject performing the action.",
      ],
      [
        "The storm damaged the roof.",
        "Which noun performs the action?",
        "The storm",
        "The roof",
        "The storm is the grammatical subject causing the damage.",
      ],
      [
        "The mural was restored last summer.",
        "Why might passive voice be useful here?",
        "It focuses on the mural when the restorer is not the focus",
        "It proves nobody restored the mural",
        "Passive voice can foreground the recipient without denying an actor.",
      ],
    ],
  },
  {
    grade: 9,
    slug: "literary_evidence",
    name: "Strong literary evidence",
    strand: "Reading literature",
    code: "RL.9-10.1",
    hint: "Select evidence that directly supports the interpretation, and keep inference separate from certainty.",
    cases: [
      [
        "After receiving the award, Inez placed it behind old books and changed the subject whenever it was mentioned.",
        "Which interpretation has the strongest support?",
        "Inez is uncomfortable with attention to the award",
        "Inez definitely stole the award",
        "Concealment and avoidance support discomfort, but not a specific hidden cause.",
      ],
      [
        "The narrator calls the town welcoming, yet every door closes as the traveler approaches.",
        "Which tension should a reader examine?",
        "The gap between the narrator's claim and the described actions",
        "Whether every building has the same color",
        "The contradiction raises questions about the stated welcome.",
      ],
      [
        "Malik promises to leave, then silently repairs the gate before dawn.",
        "Which inference is supported?",
        "His actions suggest continuing attachment or responsibility",
        "He has forgotten how to repair gates",
        "Repairing the gate complicates his stated intention to leave.",
      ],
    ],
  },
  {
    grade: 9,
    slug: "rhetoric",
    name: "Rhetorical purpose and appeals",
    strand: "Reading informational text",
    code: "RI.9-10.6",
    hint: "Consider audience, purpose, and what kind of support the writer uses.",
    cases: [
      [
        "A speaker opens a recycling proposal with local landfill measurements and collection costs.",
        "What appeal is emphasized?",
        "Reasoning from data and costs",
        "An unrelated personal insult",
        "Quantified evidence supports a practical argument.",
      ],
      [
        "A flood-preparation speech describes a family's evacuation before presenting a safety plan.",
        "What is the likely function of the opening story?",
        "Make the consequences concrete for the audience",
        "Prove every family has the same experience",
        "The example gives the issue human significance without proving universality.",
      ],
      [
        "A transit report explains that its authors measured travel times over six months.",
        "What does this detail help establish?",
        "The basis and credibility of the report's evidence",
        "That no measurement error is possible",
        "A method helps readers evaluate credibility, not assume perfection.",
      ],
    ],
  },
  {
    grade: 9,
    slug: "research",
    name: "Evaluating research sources",
    strand: "Research writing",
    code: "W.9-10.8",
    hint: "Check expertise, method, date, evidence, and possible interests rather than appearance alone.",
    cases: [
      [
        "A study reports its sample, methods, limitations, and funding. An advertisement provides only a testimonial.",
        "Which is easier to evaluate systematically?",
        "The study with disclosed methods",
        "The testimonial solely because it sounds confident",
        "Disclosed methods and limits make claims inspectable.",
      ],
      [
        "A page cites a statistic but links only to another page repeating the same sentence.",
        "What is the best next step?",
        "Find the original data source and context",
        "Treat repetition as independent confirmation",
        "Repeated claims may share one unverified origin.",
      ],
      [
        "A ten-year-old report describes the current population of a fast-growing city.",
        "What needs checking before using it as current evidence?",
        "Whether newer population data are available",
        "Whether its font looks modern",
        "The statistic's time relevance matters for a current claim.",
      ],
    ],
  },
  {
    grade: 9,
    slug: "parallelism",
    name: "Parallel structure",
    strand: "Language",
    code: "L.9-10.1",
    hint: "Items doing the same grammatical job should use matching grammatical forms.",
    cases: [
      [
        "Draft: The club values honesty, patience, and being kind.",
        "Which revision creates parallel nouns?",
        "The club values honesty, patience, and kindness",
        "The club values honest, patience, and kindness",
        "All three revised items are nouns.",
      ],
      [
        "Draft: She likes hiking, swimming, and to cycle.",
        "Which revision is parallel?",
        "She likes hiking, swimming, and cycling",
        "She likes hike, swimming, and cycling",
        "All three activities use the same -ing form.",
      ],
      [
        "Draft: The plan is clear, affordable, and it can work.",
        "Which revision uses parallel adjectives?",
        "The plan is clear, affordable, and practical",
        "The plan is clarity, affordable, and practical",
        "Matching adjectives make the coordinated description consistent.",
      ],
    ],
  },
  {
    grade: 10,
    slug: "theme_development",
    name: "Tracing theme across a passage",
    strand: "Reading literature",
    code: "RL.9-10.2",
    hint: "Trace changes and repeated choices; avoid turning a complex passage into an absolute slogan.",
    cases: [
      [
        "At first, Tessa guards her discovery. When the machine fails, she shares her notes; the group improves it, though she still fears losing credit.",
        "Which theme reflects the whole passage?",
        "Collaboration can help progress while challenging personal ambition",
        "Sharing instantly removes every conflict",
        "The ending preserves tension even as cooperation helps.",
      ],
      [
        "A village celebrates a new dam. Later, reduced water downstream forces a public debate about who benefits.",
        "Which theme is developed?",
        "Progress can distribute benefits and costs unevenly",
        "Every new technology is entirely harmful",
        "The passage includes benefits and later tradeoffs.",
      ],
      [
        "A former rival helps rebuild a shop, but its owner needs time before trusting him.",
        "Which thematic statement fits?",
        "Repairing trust can require actions and time",
        "One kind act always erases the past",
        "The delayed trust connects actions with an ongoing process.",
      ],
    ],
  },
  {
    grade: 10,
    slug: "argument_validity",
    name: "Reasoning, evidence, and fallacies",
    strand: "Reading informational text",
    code: "RI.9-10.8",
    hint: "Ask whether the conclusion follows and whether other explanations or options were excluded without evidence.",
    cases: [
      [
        "Sales increased after the store changed its logo. The owner says the logo must be the sole cause.",
        "What is the reasoning problem?",
        "Sequence alone does not establish sole causation",
        "Sales can never be measured",
        "Other changes could explain the increase.",
      ],
      [
        "A writer says a town must either close all roads or accept constant gridlock.",
        "What should readers question?",
        "Whether reasonable alternatives have been excluded",
        "Whether towns contain roads",
        "The argument presents only two options without ruling out others.",
      ],
      [
        "A report recommends a policy because a famous actor supports it, without discussing relevant evidence.",
        "What is missing?",
        "Evidence relevant to the policy's effects",
        "More details about the actor's clothing",
        "Popularity does not establish the policy's effectiveness.",
      ],
    ],
  },
  {
    grade: 10,
    slug: "synthesis",
    name: "Synthesizing multiple sources",
    strand: "Research writing",
    code: "W.9-10.8",
    hint: "Combine complementary findings while preserving each source's scope and limits.",
    cases: [
      [
        "Source A finds shaded streets are cooler. Source B finds tree maintenance costs vary by species.",
        "Which synthesis uses both?",
        "Tree planting plans should consider cooling benefits and maintenance costs",
        "Trees cost nothing because they provide shade",
        "The synthesis connects a benefit with a planning constraint.",
      ],
      [
        "One survey reports student preferences; another study measures test performance.",
        "How should a writer combine them?",
        "Distinguish preferences from measured learning outcomes",
        "Treat preferences and performance as identical",
        "The sources answer different questions and should retain that distinction.",
      ],
      [
        "Two studies find different effects but use different age groups and durations.",
        "Which synthesis is most careful?",
        "Effects may depend on population or duration, requiring further comparison",
        "One study must be fraudulent",
        "Different conditions can contribute to different findings.",
      ],
    ],
  },
  {
    grade: 10,
    slug: "connotation",
    name: "Diction, connotation, and tone",
    strand: "Language and craft",
    code: "RL.9-10.4",
    hint: "Words can share a basic referent while suggesting different judgments or emotions.",
    cases: [
      [
        "One narrator calls a character determined; another calls the same behavior stubborn.",
        "What changes between the descriptions?",
        "The judgment implied by the word choice",
        "The character's name",
        "Determined is often approving, while stubborn suggests unreasonable resistance.",
      ],
      [
        "A room is described as either cozy or cramped.",
        "Which distinction matters?",
        "Cozy suggests comfort; cramped emphasizes restricted space",
        "Both words necessarily describe different room sizes",
        "Connotations frame similar physical conditions differently.",
      ],
      [
        "A narrator describes officials as slithering into the meeting.",
        "What effect does slithering likely create?",
        "A suspicious or hostile tone",
        "A neutral attendance record",
        "The animal-associated verb adds negative judgment beyond simple movement.",
      ],
    ],
  },
];

export const secondaryLiteracy: SkillContent[] = scopes.map((s) => ({
  id: `g${s.grade}_english_${s.slug}`,
  name: s.name,
  grade: s.grade,
  subject: "English",
  domain: s.strand,
  topic: s.name,
  objective: `${s.name}: justify an interpretation using specific textual evidence.`,
  prerequisites: [],
  misconceptions: [],
  strategies: ["evidence_first", "guided_annotation", "compare_contrast"],
  standards: [
    {
      framework: "CCSS",
      reference: s.code,
      source: `https://www.thecorestandards.org/ELA-Literacy/${s.code.split(".")[0]}/${s.grade >= 9 ? "9-10" : s.grade}/`,
      alignment: "scope-reference",
    },
  ],
  status: "draft",
  reviewer: null,
  curriculumVersion: "us-secondary-v1",
  provenance:
    "Original short passages and practice; standards scope reference, pending educator review. Micro-passages do not replace sustained grade-level reading or writing.",
  questions: s.cases.map(
    ([passage, question, answer, distractor, reason], i) => ({
      role: (["diagnostic", "practice", "mastery"] as const)[i],
      prompt: `${passage}\n${question}`,
      answer,
      choices: i % 2 ? [distractor, answer] : [answer, distractor],
      hint: s.hint,
      explanation: reason,
      context: `Separate the claim from its supporting detail. ${s.hint}`,
      visuals: [{ type: "passage", text: passage, highlights: [] }],
      responseType: "short",
    }),
  ),
  glossary: {
    evidence:
      "Evidence is a specific observation or detail that supports or challenges a claim.",
    inference:
      "An inference combines textual clues with reasoning; it is not necessarily certain.",
    theme:
      "A theme is an idea about life or human experience developed through a work.",
    claim:
      "A claim is an assertion that can be supported or challenged with reasons and evidence.",
  },
  rubric: {
    criteria: [
      {
        id: "evidence",
        description: "Refer to specific textual evidence.",
        terms: ["detail", "text", "passage", "words", "evidence"],
        weight: 1,
      },
      {
        id: "reason",
        description: "Explain how the evidence supports the interpretation.",
        terms: ["because", "suggests", "supports", "shows", "rather than"],
        weight: 1,
      },
    ],
    minScore: 0.75,
    counterEvidence: [],
    sampleExplanation: s.cases[0][4],
  },
}));
