import type { SkillContent } from "./schema";

type Case = [
  scenario: string,
  question: string,
  answer: string,
  distractor: string,
  explanation: string,
];
interface Scope {
  grade: number;
  subject: "Science" | "Social Studies";
  slug: string;
  name: string;
  domain: string;
  reference: string;
  hint: string;
  cases: Case[];
}
const scopes: Scope[] = [
  {
    grade: 6,
    subject: "Science",
    slug: "particles",
    name: "Particle models of matter",
    domain: "Physical science",
    reference: "MS-PS1-4",
    hint: "Distinguish particle motion and spacing from a change in the particles themselves.",
    cases: [
      [
        "A sealed sample of air is warmed.",
        "What typically increases?",
        "Average particle motion",
        "The size of each air molecule",
        "Higher temperature corresponds to greater average kinetic energy.",
      ],
      [
        "Liquid water freezes without a chemical reaction.",
        "What remains the same?",
        "The identity of the water molecules",
        "The arrangement and motion of every molecule",
        "A physical state change does not change water's chemical identity.",
      ],
      [
        "A gas spreads to fill a container.",
        "Which model explains this?",
        "Particles move freely between collisions",
        "Particles stay fixed in a rigid pattern",
        "Gas particles move through the available space.",
      ],
    ],
  },
  {
    grade: 6,
    subject: "Science",
    slug: "cells",
    name: "Cells and their structures",
    domain: "Life science",
    reference: "MS-LS1-1; MS-LS1-2",
    hint: "Connect a cell structure to the job it performs; do not assume every organism has identical cells.",
    cases: [
      [
        "A cell must regulate exchanges with its surroundings.",
        "Which structure is most directly involved?",
        "Cell membrane",
        "A leaf's entire stem",
        "The membrane regulates movement into and out of the cell.",
      ],
      [
        "A green plant cell uses light to make sugars.",
        "Which structure carries out photosynthesis?",
        "Chloroplast",
        "Cell wall",
        "Chloroplasts contain the machinery for photosynthesis; walls provide structural support.",
      ],
      [
        "A microscope reveals a single-celled organism.",
        "Which conclusion is supported?",
        "An organism can consist of one cell",
        "All organisms need many cells",
        "Unicellular organisms perform life functions within one cell.",
      ],
    ],
  },
  {
    grade: 6,
    subject: "Science",
    slug: "water_cycle",
    name: "Water cycling and energy",
    domain: "Earth science",
    reference: "MS-ESS2-4",
    hint: "Track where water moves and whether energy is absorbed or released during the change.",
    cases: [
      [
        "Sunlight warms a puddle and liquid water enters the air as vapor.",
        "Which process occurs?",
        "Evaporation",
        "Precipitation",
        "Evaporation changes liquid water to vapor using energy.",
      ],
      [
        "Water vapor cools into tiny liquid droplets in a cloud.",
        "Which process occurs?",
        "Condensation",
        "Melting",
        "Condensation changes vapor to liquid.",
      ],
      [
        "Rainwater travels downhill into a stream.",
        "Which force drives this movement?",
        "Gravity",
        "Magnetism acting on water",
        "Gravity pulls water toward lower elevations.",
      ],
    ],
  },
  {
    grade: 6,
    subject: "Science",
    slug: "ecosystems",
    name: "Energy in ecosystems",
    domain: "Life science",
    reference: "MS-LS2-3",
    hint: "Follow energy from its source through feeding relationships; matter and energy do not cycle in identical ways.",
    cases: [
      [
        "Grass is eaten by a rabbit, which is eaten by a fox.",
        "Which organism first captures sunlight as chemical energy?",
        "Grass",
        "Fox",
        "The producer captures solar energy through photosynthesis.",
      ],
      [
        "Fungi break down a fallen log.",
        "What role do the fungi play?",
        "Decomposers returning materials to the environment",
        "Producers making food from sunlight",
        "Decomposition makes matter available for reuse.",
      ],
      [
        "Only part of the energy in prey becomes biomass in a predator.",
        "What happens to much of the remaining energy?",
        "It is used in life processes and transferred as heat",
        "It is all recycled unchanged into sunlight",
        "Energy transfers include heat dissipation and metabolic use.",
      ],
    ],
  },
  {
    grade: 7,
    subject: "Science",
    slug: "reactions",
    name: "Evidence of chemical reactions",
    domain: "Physical science",
    reference: "MS-PS1-2",
    hint: "Look for evidence of new substances; a single observation may need further investigation.",
    cases: [
      [
        "Two liquids form a new solid when mixed.",
        "What does the new solid suggest?",
        "A chemical reaction may have produced a new substance",
        "Only the container changed shape",
        "A precipitate is evidence consistent with a chemical reaction.",
      ],
      [
        "Ice melts in a glass.",
        "Is melting alone evidence of a new substance?",
        "No, water remains water",
        "Yes, liquid water is a new element",
        "The state changes while chemical identity remains.",
      ],
      [
        "A sealed reaction flask has the same mass before and after gas forms.",
        "Why is this expected?",
        "Atoms remain in the closed system",
        "Gas has no mass",
        "Matter is conserved when no material enters or leaves.",
      ],
    ],
  },
  {
    grade: 7,
    subject: "Science",
    slug: "forces",
    name: "Forces and changes in motion",
    domain: "Physical science",
    reference: "MS-PS2-2",
    hint: "Consider net force, not just one force in isolation.",
    cases: [
      [
        "A box is pushed right with 8 N and left with 3 N.",
        "What is the net force?",
        "5 N to the right",
        "11 N to the left",
        "Opposing forces subtract; the larger rightward force determines direction.",
      ],
      [
        "A cart moves straight at constant speed.",
        "What is its net force in an ideal model?",
        "Zero",
        "A growing forward force",
        "Constant velocity means zero acceleration and therefore zero net force.",
      ],
      [
        "Two carts experience the same net force; one has twice the mass.",
        "Which has greater acceleration?",
        "The lighter cart",
        "Both must have the same acceleration",
        "For a fixed force, acceleration decreases as mass increases.",
      ],
    ],
  },
  {
    grade: 7,
    subject: "Science",
    slug: "photosynthesis",
    name: "Photosynthesis and respiration",
    domain: "Life science",
    reference: "MS-LS1-6; MS-LS1-7",
    hint: "Track matter separately from energy, and distinguish making sugars from releasing their stored energy.",
    cases: [
      [
        "A plant makes sugars using light.",
        "Which gas provides carbon for those sugars?",
        "Carbon dioxide",
        "Oxygen",
        "The carbon in sugar is obtained from carbon dioxide.",
      ],
      [
        "A plant's cells release usable energy from sugars at night.",
        "Which process is involved?",
        "Cellular respiration",
        "Photosynthesis without light",
        "Plant cells respire as well as photosynthesize.",
      ],
      [
        "A seedling gains dry mass as it grows.",
        "Where does much of the carbon in that mass originate?",
        "Carbon dioxide from the air",
        "Sunlight becoming carbon atoms",
        "Light supplies energy; carbon dioxide supplies carbon atoms.",
      ],
    ],
  },
  {
    grade: 7,
    subject: "Science",
    slug: "plates",
    name: "Plate tectonics evidence",
    domain: "Earth science",
    reference: "MS-ESS2-3",
    hint: "Connect patterns in rocks, fossils, and landforms to a mechanism rather than to a single coincidence.",
    cases: [
      [
        "Matching fossils occur in rocks on continents now separated by an ocean.",
        "What does this support?",
        "The continents were once connected or closer",
        "The organisms crossed the modern ocean daily",
        "Matching ancient evidence supports past geographic connections.",
      ],
      [
        "New ocean crust forms at a mid-ocean ridge.",
        "What plate motion occurs there?",
        "Plates move apart",
        "Plates remain perfectly fixed",
        "Divergence allows magma to form new crust.",
      ],
      [
        "Earthquake locations form a narrow belt along a plate boundary.",
        "What is the best explanation?",
        "Plate interactions concentrate deformation",
        "Earthquakes occur only where people live",
        "Boundary motion concentrates stress and deformation.",
      ],
    ],
  },
  {
    grade: 8,
    subject: "Science",
    slug: "waves",
    name: "Wave properties",
    domain: "Physical science",
    reference: "MS-PS4-1",
    hint: "Distinguish frequency, wavelength, and amplitude; state what is held constant.",
    cases: [
      [
        "Two sound waves in the same medium have different frequencies.",
        "Which has higher pitch?",
        "The higher-frequency wave",
        "The larger-amplitude wave regardless of frequency",
        "Pitch is associated with frequency, while amplitude relates to intensity.",
      ],
      [
        "A wave's speed stays fixed while its frequency doubles.",
        "What happens to wavelength?",
        "It halves",
        "It doubles",
        "Since speed = frequency × wavelength, constant speed requires inverse change.",
      ],
      [
        "Two waves differ only in amplitude.",
        "Which quantity is unchanged?",
        "Frequency",
        "Maximum displacement",
        "Amplitude changes displacement, not necessarily frequency.",
      ],
    ],
  },
  {
    grade: 8,
    subject: "Science",
    slug: "selection",
    name: "Natural selection",
    domain: "Life science",
    reference: "MS-LS4-4",
    hint: "Selection acts on existing heritable variation across generations, not on an individual's wishes.",
    cases: [
      [
        "In a dark habitat, dark beetles are less visible to predators and leave more offspring.",
        "What may happen over generations?",
        "Heritable dark coloration may become more common",
        "Each beetle decides to change color",
        "Differential reproduction can change trait frequencies.",
      ],
      [
        "An insect population contains varied inherited resistance to a pesticide.",
        "Which explanation fits increased resistance after repeated use?",
        "More resistant insects survive and reproduce",
        "The pesticide teaches insects to resist it",
        "Selection favors variants that already confer a survival advantage.",
      ],
      [
        "A trait helps survival but cannot be inherited.",
        "Can that trait alone spread by genetic inheritance?",
        "No, inheritance requires a heritable basis",
        "Yes, all useful acquired traits are inherited",
        "Usefulness alone does not make a trait genetically heritable.",
      ],
    ],
  },
  {
    grade: 8,
    subject: "Science",
    slug: "earth_sun",
    name: "Earth, Sun, and seasons",
    domain: "Earth science",
    reference: "MS-ESS1-1",
    hint: "Use Earth's axial tilt and sunlight angle, not distance alone, to explain seasons.",
    cases: [
      [
        "The Northern Hemisphere tilts toward the Sun.",
        "Which seasonal pattern is expected there?",
        "Longer days and more direct sunlight",
        "Winter solely because Earth is closer",
        "Tilt changes day length and sunlight angle.",
      ],
      [
        "It is summer in the Northern Hemisphere.",
        "What season is generally occurring in the Southern Hemisphere?",
        "Winter",
        "Summer everywhere",
        "Opposite hemispheres tilt toward and away from the Sun at the same time.",
      ],
      [
        "The Moon appears half illuminated from Earth.",
        "What explains this phase?",
        "Our viewing angle of the Moon's sunlit half",
        "Earth's shadow causes every lunar phase",
        "Normal phases arise from geometry; eclipses involve shadows.",
      ],
    ],
  },
  {
    grade: 8,
    subject: "Science",
    slug: "engineering",
    name: "Engineering tradeoffs and tests",
    domain: "Engineering design",
    reference: "MS-ETS1-1; MS-ETS1-3",
    hint: "Separate success criteria from constraints and compare designs under the same conditions.",
    cases: [
      [
        "A filter must remove visible particles and cost less than $20.",
        "Which is a constraint?",
        "The $20 cost limit",
        "The designer's favorite color",
        "A constraint limits acceptable solutions; particle removal is a performance criterion.",
      ],
      [
        "Two bridge designs are tested with different loads.",
        "What change makes comparison fairer?",
        "Test both with the same loading procedure",
        "Choose the prettier bridge",
        "Controlled test conditions make performance comparable.",
      ],
      [
        "One design is stronger but heavier than another.",
        "How should designers decide?",
        "Compare both against agreed criteria and constraints",
        "Assume heavier always means better",
        "Tradeoffs depend on what the design must accomplish.",
      ],
    ],
  },
  {
    grade: 9,
    subject: "Science",
    slug: "cell_systems",
    name: "Cell systems and homeostasis",
    domain: "Biology",
    reference: "HS-LS1-2; HS-LS1-3",
    hint: "Explain how interacting parts regulate conditions, using a feedback mechanism.",
    cases: [
      [
        "Body temperature rises and sweating increases.",
        "What kind of response is this?",
        "Negative feedback opposing the change",
        "Positive feedback increasing the original temperature rise",
        "Evaporation helps cool the body, counteracting the initial change.",
      ],
      [
        "Blood glucose rises after a meal and insulin promotes uptake into cells.",
        "What is the regulatory effect?",
        "It helps return blood glucose toward its usual range",
        "It ensures glucose rises without limit",
        "The response opposes the initial increase.",
      ],
      [
        "Muscle activity requires coordinated respiratory and circulatory function.",
        "Why do these systems interact?",
        "To transport needed gases and materials to cells",
        "Because every organ performs the identical job",
        "Different specialized systems cooperate to meet cellular needs.",
      ],
    ],
  },
  {
    grade: 9,
    subject: "Science",
    slug: "genetics",
    name: "Inheritance and probability",
    domain: "Biology",
    reference: "HS-LS3-3",
    hint: "A genetic model predicts probabilities; it does not guarantee the outcome for each individual.",
    cases: [
      [
        "In a simple Mendelian model, two Aa parents each pass A or a with equal probability.",
        "What fraction of offspring is expected to be aa?",
        "1/4",
        "3/4",
        "Only the a-from-both combination gives aa: 1/2 × 1/2.",
      ],
      [
        "A model predicts a 1/4 chance of a trait.",
        "Must exactly one of four offspring have it?",
        "No, probabilities describe expected patterns over many outcomes",
        "Yes, every group of four must match",
        "Small samples vary randomly around expected proportions.",
      ],
      [
        "A plant's height depends on several genes and growing conditions.",
        "Which explanation is most appropriate?",
        "Both inherited and environmental factors contribute",
        "One simple dominant allele must explain all height variation",
        "Many traits have complex genetic and environmental influences.",
      ],
    ],
  },
  {
    grade: 9,
    subject: "Science",
    slug: "carbon",
    name: "Carbon cycling",
    domain: "Biology",
    reference: "HS-LS2-5",
    hint: "Track carbon atoms among reservoirs; energy enters and leaves the system differently.",
    cases: [
      [
        "A tree incorporates atmospheric carbon into sugars.",
        "Which process moves that carbon?",
        "Photosynthesis",
        "Evaporation",
        "Photosynthesis incorporates carbon dioxide into organic molecules.",
      ],
      [
        "Wood burns in oxygen.",
        "Where does much of its carbon go?",
        "Into atmospheric carbon dioxide",
        "It ceases to exist",
        "Combustion rearranges atoms into products, including carbon dioxide.",
      ],
      [
        "Decomposers consume dead leaves and respire.",
        "What is one carbon transfer?",
        "Organic carbon can return to air as carbon dioxide",
        "All leaf carbon turns into sunlight",
        "Respiration transfers carbon from organic molecules to carbon dioxide.",
      ],
    ],
  },
  {
    grade: 9,
    subject: "Science",
    slug: "evolution",
    name: "Evidence for common ancestry",
    domain: "Biology",
    reference: "HS-LS4-1",
    hint: "Use multiple independent lines of evidence and distinguish ancestry from identical present-day function.",
    cases: [
      [
        "Two species share many DNA sequences and similar underlying limb structures.",
        "What does this evidence support?",
        "Common ancestry",
        "Identical habitats are required",
        "Genetic and structural similarities can support shared ancestry.",
      ],
      [
        "A fossil sequence shows gradual changes in a lineage over time.",
        "What does it provide?",
        "Evidence of historical change",
        "Proof that every species changes at the same rate",
        "Fossils document particular historical patterns, not a universal rate.",
      ],
      [
        "Bird wings and human arms have corresponding bones but different functions.",
        "Why can they inform ancestry?",
        "Shared structural organization can persist despite different uses",
        "Different functions rule out common ancestry",
        "Homologous structures can be modified for different functions.",
      ],
    ],
  },
  {
    grade: 10,
    subject: "Science",
    slug: "atoms",
    name: "Atomic structure and periodic patterns",
    domain: "Chemistry",
    reference: "HS-PS1-1",
    hint: "Distinguish protons, neutrons, and electrons and connect outer electrons to chemical behavior.",
    cases: [
      [
        "An atom contains 8 protons.",
        "What is its atomic number?",
        "8",
        "The sum of protons and neutrons",
        "Atomic number counts protons.",
      ],
      [
        "Two atoms have the same number of protons but different numbers of neutrons.",
        "What are they?",
        "Isotopes of the same element",
        "Necessarily different elements",
        "Proton count identifies the element; neutron count distinguishes isotopes.",
      ],
      [
        "Two main-group elements lie in the same periodic-table group.",
        "What pattern often helps explain similar reactivity?",
        "Similar numbers of valence electrons",
        "Identical total atomic masses",
        "Outer-electron patterns contribute to chemical similarities.",
      ],
    ],
  },
  {
    grade: 10,
    subject: "Science",
    slug: "conservation",
    name: "Conservation in chemical reactions",
    domain: "Chemistry",
    reference: "HS-PS1-7",
    hint: "Balance atom counts by changing coefficients, not by changing chemical formulas.",
    cases: [
      [
        "The equation is 2H2 + O2 → 2H2O.",
        "How many oxygen atoms occur on each side?",
        "2",
        "4",
        "One O2 contains two oxygen atoms; two water molecules contain two in total.",
      ],
      [
        "A student balances a reaction by changing H2O into H2O2.",
        "Why is this invalid?",
        "Changing a subscript changes the substance",
        "Subscripts never affect atom counts",
        "Balancing preserves identities while changing amounts through coefficients.",
      ],
      [
        "A sealed reaction starts with 12 g of reactants and nothing escapes.",
        "What total product mass is expected?",
        "12 g",
        "0 g because reactants were used up",
        "Atoms are rearranged, so total mass remains conserved.",
      ],
    ],
  },
  {
    grade: 10,
    subject: "Science",
    slug: "reaction_energy",
    name: "Energy changes in reactions",
    domain: "Chemistry",
    reference: "HS-PS1-4",
    hint: "Define the system and surroundings before interpreting the direction of energy transfer.",
    cases: [
      [
        "A reaction transfers heat from the reacting chemicals to the surroundings.",
        "How is it classified?",
        "Exothermic",
        "Endothermic",
        "Exothermic reactions release energy to their surroundings.",
      ],
      [
        "An instant cold pack absorbs heat from a hand.",
        "How is the pack's process classified?",
        "Endothermic",
        "Exothermic",
        "The process absorbs energy from its surroundings.",
      ],
      [
        "A student says breaking chemical bonds releases energy.",
        "What correction is needed?",
        "Breaking bonds requires energy; forming bonds releases energy",
        "Both processes always require no energy",
        "Net reaction energy depends on the balance between bond breaking and bond formation.",
      ],
    ],
  },
  {
    grade: 10,
    subject: "Science",
    slug: "motion_energy",
    name: "Quantitative motion and energy",
    domain: "Physics",
    reference: "HS-PS2-1; HS-PS3-1",
    hint: "Identify the relevant quantities and hold other variables constant when comparing changes.",
    cases: [
      [
        "A 2 kg object has acceleration 3 m/s².",
        "What net force acts on it?",
        "6 N",
        "1.5 N",
        "Newton's second law gives F = ma = 2 × 3 = 6 N.",
      ],
      [
        "An object's mass stays constant while its speed doubles.",
        "What happens to its kinetic energy?",
        "It becomes four times as large",
        "It merely doubles",
        "Kinetic energy is proportional to speed squared.",
      ],
      [
        "A lifted object gains gravitational potential energy while the lifting system does work.",
        "Which statement describes the transfer?",
        "Work transfers energy into the object-Earth system",
        "Energy is created from nothing",
        "Energy changes storage form through work; it is not created.",
      ],
    ],
  },
  {
    grade: 6,
    subject: "Social Studies",
    slug: "sources",
    name: "Primary and secondary sources",
    domain: "Historical inquiry",
    reference: "C3 Dimension 2: History; Dimension 3: Sources",
    hint: "Classify a source in relation to the historical question, not by whether it seems trustworthy.",
    cases: [
      [
        "A researcher studies a nineteenth-century voyage using a sailor's diary from that voyage.",
        "What kind of source is the diary for that question?",
        "Primary source",
        "Modern secondary summary",
        "The diary is a record produced by a participant during the event.",
      ],
      [
        "A historian writes a modern book interpreting several ancient letters.",
        "What is the book?",
        "A secondary interpretation",
        "An ancient eyewitness letter",
        "The book analyzes earlier evidence rather than originating in the ancient event.",
      ],
      [
        "An eyewitness remembers an event incorrectly.",
        "Does primary-source status guarantee accuracy?",
        "No, source claims still need evaluation",
        "Yes, eyewitnesses cannot be mistaken",
        "Proximity to an event does not remove bias or memory limits.",
      ],
    ],
  },
  {
    grade: 6,
    subject: "Social Studies",
    slug: "geography",
    name: "Geography and settlement",
    domain: "Geography",
    reference: "C3 Dimension 2: Geography",
    hint: "Identify how environmental conditions create opportunities and constraints without assuming they determine every decision.",
    cases: [
      [
        "A settlement grows near a navigable river and fertile soil.",
        "Which explanation is supported?",
        "Transport and farming opportunities can attract settlement",
        "Rivers guarantee that conflict never occurs",
        "The features offer useful resources but do not guarantee every outcome.",
      ],
      [
        "A mountain range separates two communities.",
        "What is a plausible effect?",
        "Travel and exchange may be more difficult",
        "The communities can never communicate",
        "Terrain can constrain movement without making it impossible.",
      ],
      [
        "A port expands after improved roads connect it to inland farms.",
        "What relationship does this show?",
        "Transport networks connect production and trade",
        "Ports develop independently of transport",
        "The roads link producers to a trading location.",
      ],
    ],
  },
  {
    grade: 6,
    subject: "Social Studies",
    slug: "scarcity",
    name: "Scarcity and opportunity cost",
    domain: "Economics",
    reference: "C3 Dimension 2: Economics",
    hint: "Opportunity cost is the next-best alternative given up, not every imaginable alternative.",
    cases: [
      [
        "A town can fund either a playground or its next-best option, a library repair, but not both. It chooses the playground.",
        "What is the opportunity cost?",
        "The forgone library repair",
        "The playground itself",
        "Choosing uses limited resources and gives up the next-best option.",
      ],
      [
        "A student has one free hour and chooses practice instead of the next-best option, reading.",
        "What is the opportunity cost?",
        "The reading time forgone",
        "All future reading forever",
        "The cost concerns the relevant alternative in that decision.",
      ],
      [
        "A community has more desired projects than available workers and funds.",
        "Which economic condition does this illustrate?",
        "Scarcity",
        "Unlimited resources",
        "Wants exceed available resources, requiring choices.",
      ],
    ],
  },
  {
    grade: 6,
    subject: "Social Studies",
    slug: "civic_rules",
    name: "Rules, authority, and public decisions",
    domain: "Civics",
    reference: "C3 Dimension 2: Civics",
    hint: "Consider the purpose of a rule, who has authority, and how decisions can be questioned through established processes.",
    cases: [
      [
        "Residents disagree about park hours and attend a public meeting.",
        "What civic practice is illustrated?",
        "Participation in local decision-making",
        "Elimination of all disagreement",
        "Public participation lets residents contribute to a decision.",
      ],
      [
        "A rule protects a shared water supply by limiting waste.",
        "What is its stated public purpose?",
        "Protecting a shared resource",
        "Guaranteeing every person agrees",
        "The rule addresses resource use, not unanimity.",
      ],
      [
        "A student compares reasons for and against a school policy.",
        "Which skill is being used?",
        "Evaluating competing arguments",
        "Avoiding all evidence",
        "Comparing reasons supports informed judgment.",
      ],
    ],
  },
  {
    grade: 7,
    subject: "Social Studies",
    slug: "trade",
    name: "Trade and interdependence",
    domain: "World history and economics",
    reference: "C3 Dimension 2: Economics and History",
    hint: "Trade can exchange goods and ideas and create mutual dependence; effects need not be equal for everyone.",
    cases: [
      [
        "One region exports grain and imports metal tools.",
        "What does this show?",
        "Economic interdependence",
        "Complete self-sufficiency",
        "The region relies partly on exchange with others.",
      ],
      [
        "Merchants carry goods along with languages and technologies.",
        "Which process may accompany trade?",
        "Cultural diffusion",
        "Automatic disappearance of all local customs",
        "Interactions can spread ideas without erasing every local tradition.",
      ],
      [
        "A disrupted trade route raises costs for communities relying on imported food.",
        "What does this reveal?",
        "Dependence on networks can create vulnerability",
        "Trade has no effect on consumers",
        "Supply disruption affects communities connected to the route.",
      ],
    ],
  },
  {
    grade: 7,
    subject: "Social Studies",
    slug: "perspective",
    name: "Historical perspective",
    domain: "Historical inquiry",
    reference: "C3 Dimension 2: History; Dimension 3: Sources",
    hint: "Ask who produced the source, for whom, for what purpose, and what they could observe.",
    cases: [
      [
        "A ruler's inscription describes only victories.",
        "What should a historian consider?",
        "Its purpose may be to legitimize the ruler",
        "It must contain every viewpoint",
        "Official celebration can select favorable events.",
      ],
      [
        "A merchant and a farmer describe the same new tax differently.",
        "What may explain the difference?",
        "Their economic positions shape their concerns",
        "One must be unable to read",
        "Different interests can produce differing perspectives.",
      ],
      [
        "A later account judges an ancient action using only today's assumptions.",
        "What should be added?",
        "Evidence about the historical context",
        "A claim that context excuses every action",
        "Context aids explanation without requiring moral approval.",
      ],
    ],
  },
  {
    grade: 7,
    subject: "Social Studies",
    slug: "government",
    name: "Comparing forms of government",
    domain: "Civics",
    reference: "C3 Dimension 2: Civics",
    hint: "Compare how authority is acquired, limited, and held accountable rather than relying on a label alone.",
    cases: [
      [
        "A constitution divides powers among institutions.",
        "What is one purpose?",
        "Limit concentration of authority",
        "Guarantee leaders never disagree",
        "Division can constrain any one institution's power.",
      ],
      [
        "Citizens elect representatives who make laws.",
        "Which feature is described?",
        "Representative government",
        "Hereditary succession alone",
        "Selection by voters distinguishes the described process.",
      ],
      [
        "A leader claims unlimited authority with no effective legal checks.",
        "Which concern follows?",
        "Lack of institutional accountability",
        "Too many independent vetoes by definition",
        "Unconstrained authority limits mechanisms for challenge.",
      ],
    ],
  },
  {
    grade: 7,
    subject: "Social Studies",
    slug: "migration",
    name: "Migration and human-environment interaction",
    domain: "Geography",
    reference: "C3 Dimension 2: Geography",
    hint: "Distinguish pressures to leave from attractions to a destination, and allow multiple causes.",
    cases: [
      [
        "Crop failure drives families to seek work elsewhere.",
        "Which factor encourages departure?",
        "Loss of livelihood",
        "A new job at the destination",
        "The loss is a pressure at the origin.",
      ],
      [
        "A city attracts workers with new factory jobs.",
        "Which factor attracts migrants?",
        "Employment opportunities",
        "Crop failure at every origin is proven",
        "The scenario states an attraction, not all possible causes.",
      ],
      [
        "Migration changes language use and labor supply in a growing town.",
        "Which conclusion is supported?",
        "Migration can affect both cultural and economic life",
        "Migration has only one kind of effect",
        "The scenario names effects in two domains.",
      ],
    ],
  },
  {
    grade: 8,
    subject: "Social Studies",
    slug: "constitution",
    name: "Constitutional checks and balances",
    domain: "US civics",
    reference: "C3 Dimension 2: Civics",
    hint: "Distinguish the jobs of branches from mechanisms that limit another branch's actions.",
    cases: [
      [
        "The US president vetoes a bill passed by Congress.",
        "What does this illustrate?",
        "An executive check on legislation",
        "A court writing a statute",
        "The veto is an executive power affecting legislation.",
      ],
      [
        "Congress overrides a presidential veto with the required supermajority.",
        "What does this illustrate?",
        "A legislative check on the executive",
        "The president overruling Congress again",
        "The legislature can act despite the veto when constitutional requirements are met.",
      ],
      [
        "A court reviews whether a law conflicts with the Constitution.",
        "Which principle is involved?",
        "Judicial review",
        "Hereditary monarchy",
        "Judicial review examines constitutional compatibility.",
      ],
    ],
  },
  {
    grade: 8,
    subject: "Social Studies",
    slug: "historical_causes",
    name: "Multiple causes in US history",
    domain: "US history",
    reference: "C3 Dimension 2: History",
    hint: "Distinguish an immediate trigger from longer-term conditions; do not reduce a complex event to one detail.",
    cases: [
      [
        "A protest follows a new tax amid years of disagreement over representation.",
        "Which distinction is useful?",
        "The tax can be a trigger while representation is a longer-term issue",
        "Only the most recent event can be a cause",
        "Events can have immediate and structural causes.",
      ],
      [
        "A historian explains industrial growth using resources, labor, investment, and transport.",
        "What kind of explanation is this?",
        "A multicausal explanation",
        "A claim that one factor explains everything",
        "Several interacting factors are considered.",
      ],
      [
        "Two events occur in the same year.",
        "What is needed to argue one caused the other?",
        "Evidence of a causal connection",
        "Their shared date alone",
        "Chronological proximity does not establish causation.",
      ],
    ],
  },
  {
    grade: 8,
    subject: "Social Studies",
    slug: "rights",
    name: "Rights and civic participation",
    domain: "US civics",
    reference: "C3 Dimension 2: Civics",
    hint: "Identify the civic action and distinguish exercising a right from guaranteeing a desired result.",
    cases: [
      [
        "Residents peacefully petition officials to change a policy.",
        "What are they doing?",
        "Participating through a petition",
        "Automatically replacing the government",
        "Petitioning communicates a request; it does not guarantee adoption.",
      ],
      [
        "A newspaper criticizes a public policy using evidence.",
        "Which civic function can this serve?",
        "Informing debate and scrutinizing decisions",
        "Preventing everyone from disagreeing",
        "Public criticism can contribute to accountability and debate.",
      ],
      [
        "Eligible voters compare candidates' records and proposals.",
        "What supports an informed choice?",
        "Evaluating reliable evidence about their positions",
        "Choosing solely by poster size",
        "Evidence about relevant actions and proposals supports informed participation.",
      ],
    ],
  },
  {
    grade: 8,
    subject: "Social Studies",
    slug: "economic_change",
    name: "Industrialization and economic change",
    domain: "US history and economics",
    reference: "C3 Dimension 2: Economics and History",
    hint: "Consider production, labor, and distributional effects instead of assuming all groups experience change identically.",
    cases: [
      [
        "Machines increase output per worker in a factory.",
        "What has increased?",
        "Labor productivity",
        "The number of hours in a day",
        "Productivity measures output relative to labor input.",
      ],
      [
        "A railroad lowers the cost of moving farm goods to cities.",
        "What effect is plausible?",
        "Farmers gain access to wider markets",
        "Distance becomes physically zero",
        "Lower transport costs can expand feasible trade.",
      ],
      [
        "Factory expansion creates jobs but also unsafe working conditions.",
        "Which account is most complete?",
        "Discuss both opportunities and costs",
        "Mention only one effect as if it were the whole story",
        "A fuller explanation considers different consequences.",
      ],
    ],
  },
  {
    grade: 9,
    subject: "Social Studies",
    slug: "corroboration",
    name: "Corroborating historical claims",
    domain: "World history inquiry",
    reference: "C3 Dimension 3: Evaluating Sources and Using Evidence",
    hint: "Independent agreement matters more than many copies of the same original claim.",
    cases: [
      [
        "Three websites repeat a single unsourced account.",
        "How much independent corroboration is established?",
        "None merely from repetition",
        "Three independent confirmations",
        "The sites may share one source and one error.",
      ],
      [
        "A trade claim is supported by port records and independently excavated goods.",
        "Why is this stronger?",
        "Different kinds of evidence converge",
        "Archaeology can never be mistaken",
        "Independent evidence can support the same interpretation.",
      ],
      [
        "Two contemporary accounts disagree about crowd size.",
        "What should a historian do?",
        "Compare vantage points, purposes, and other evidence",
        "Average the numbers without examining their basis",
        "Source conditions affect the reliability of estimates.",
      ],
    ],
  },
  {
    grade: 9,
    subject: "Social Studies",
    slug: "revolutions",
    name: "Explaining political change",
    domain: "World history",
    reference: "C3 Dimension 2: History and Civics",
    hint: "Separate grievances, ideas, institutions, and triggering events in a causal explanation.",
    cases: [
      [
        "A movement combines economic grievances with demands for political representation.",
        "Which explanation fits?",
        "Economic and political factors interact",
        "Only ideas can ever matter",
        "The scenario gives factors in both domains.",
      ],
      [
        "A new constitution follows a revolution but excludes some groups from voting.",
        "What should an evaluation consider?",
        "Both institutional change and continuing exclusion",
        "Assume all inequality ended immediately",
        "Political change can coexist with limits on participation.",
      ],
      [
        "A government adopts reforms after organized public pressure.",
        "What connection should be investigated?",
        "How collective action influenced institutional decisions",
        "Whether history occurs without human action",
        "The timing invites investigation of the mechanism of influence.",
      ],
    ],
  },
  {
    grade: 9,
    subject: "Social Studies",
    slug: "markets",
    name: "Supply, demand, and incentives",
    domain: "Economics",
    reference: "C3 Dimension 2: Economics",
    hint: "State which factor changes and hold other influences constant in a simple model.",
    cases: [
      [
        "Demand rises while supply conditions stay unchanged in a competitive market.",
        "What price pressure is expected in the simple model?",
        "Upward pressure",
        "Guaranteed zero prices",
        "More buyers competing for available supply tends to raise price.",
      ],
      [
        "Improved production technology lowers costs, other things equal.",
        "What may happen to supply?",
        "It can increase",
        "It must disappear",
        "Lower costs can make more output profitable at a given price.",
      ],
      [
        "A subsidy reduces the private cost of installing insulation.",
        "What incentive does this create?",
        "Greater encouragement to install insulation",
        "A guarantee every household participates",
        "Lower cost can influence choices without determining everyone's behavior.",
      ],
    ],
  },
  {
    grade: 9,
    subject: "Social Studies",
    slug: "global_networks",
    name: "Global networks and exchange",
    domain: "World geography",
    reference: "C3 Dimension 2: Geography and History",
    hint: "Trace connections and unequal effects at local and global scales.",
    cases: [
      [
        "A product's design, parts, assembly, and sales occur in different countries.",
        "What does this illustrate?",
        "A global production network",
        "One country's complete isolation",
        "Production links multiple places through specialized activities.",
      ],
      [
        "A shipping disruption affects factories far from the blocked port.",
        "Why can effects spread?",
        "Factories rely on connected supply chains",
        "Physical distance prevents all economic connections",
        "Dependencies transmit disruption across the network.",
      ],
      [
        "A new trade connection benefits exporters but increases competition for some local producers.",
        "Which conclusion is supported?",
        "Effects vary among groups",
        "All groups gain equally by definition",
        "Benefits and costs depend on each group's position.",
      ],
    ],
  },
  {
    grade: 10,
    subject: "Social Studies",
    slug: "historical_argument",
    name: "Constructing historical arguments",
    domain: "Historical inquiry",
    reference: "C3 Dimension 4: Communicating Conclusions",
    hint: "Connect a defensible claim to evidence and reasoning while addressing counterevidence.",
    cases: [
      [
        "A writer claims transport drove urban growth and cites population maps plus railway expansion records.",
        "What is still needed?",
        "Reasoning connecting the evidence to the claim",
        "Only a longer title",
        "Evidence needs an explanation of its significance and causal limits.",
      ],
      [
        "A source contradicts part of a thesis.",
        "What is the strongest response?",
        "Evaluate it and qualify or revise the thesis if warranted",
        "Hide the source because it is inconvenient",
        "Responsible argument addresses relevant counterevidence.",
      ],
      [
        "A conclusion says one policy improved life for everyone, but records show uneven outcomes.",
        "What revision is warranted?",
        "Specify which groups benefited and which did not",
        "Replace evidence with stronger certainty",
        "A qualified claim better matches the recorded variation.",
      ],
    ],
  },
  {
    grade: 10,
    subject: "Social Studies",
    slug: "policy",
    name: "Public policy and tradeoffs",
    domain: "Civics",
    reference: "C3 Dimension 2: Civics; Dimension 4: Informed Action",
    hint: "Compare alternatives against explicit goals, costs, evidence, and affected groups.",
    cases: [
      [
        "A city compares transit expansion with road widening under a fixed budget.",
        "What helps evaluate the options?",
        "Shared criteria for access, cost, and likely effects",
        "Choosing the option with the shortest name",
        "Common criteria support a reasoned comparison.",
      ],
      [
        "A policy's average benefit is positive, but costs fall mostly on one neighborhood.",
        "What should be examined?",
        "Distribution of benefits and burdens",
        "Only the citywide average",
        "Averages can hide unequal effects.",
      ],
      [
        "A proposed intervention has uncertain long-term effects.",
        "Which approach supports learning?",
        "A monitored pilot with predefined evaluation criteria",
        "A claim of certainty without evidence",
        "Monitoring can reveal effects and inform revision.",
      ],
    ],
  },
  {
    grade: 10,
    subject: "Social Studies",
    slug: "externalities",
    name: "Externalities and shared resources",
    domain: "Economics",
    reference: "C3 Dimension 2: Economics",
    hint: "Identify effects on people outside a transaction and distinguish private costs from wider social costs.",
    cases: [
      [
        "A factory's emissions damage nearby gardens without compensation.",
        "What is this in an economic model?",
        "A negative externality",
        "A private cost fully paid by the buyer",
        "The harm falls on others outside the transaction.",
      ],
      [
        "A restored wetland reduces downstream flooding for many residents.",
        "What does this illustrate?",
        "Benefits extending beyond the property owner",
        "Benefits limited to the construction company",
        "Effects can spill over to people not directly paying for the project.",
      ],
      [
        "Many users draw from a shared fishery faster than fish reproduce.",
        "What problem arises?",
        "Overuse of a shared resource",
        "Unlimited replenishment regardless of use",
        "Individual incentives can conflict with long-term collective sustainability.",
      ],
    ],
  },
  {
    grade: 10,
    subject: "Social Studies",
    slug: "data_claims",
    name: "Evaluating social data",
    domain: "Civic and geographic inquiry",
    reference: "C3 Dimension 3: Evaluating Sources and Using Evidence",
    hint: "Examine denominators, sampling, time periods, and uncertainty before drawing conclusions.",
    cases: [
      [
        "Town A has 20 incidents among 1,000 residents; Town B has 30 among 3,000.",
        "Which has the higher incident rate per resident?",
        "Town A",
        "Town B merely because 30 exceeds 20",
        "The rates are 2% and 1%, respectively; counts alone mislead.",
      ],
      [
        "An online poll accepts voluntary responses from visitors to one advocacy site.",
        "What limits generalization?",
        "Self-selection and a narrow sampling population",
        "Every online response is necessarily false",
        "The sample may not represent the broader population.",
      ],
      [
        "Two maps compare totals from different years using different boundaries.",
        "What should be checked first?",
        "Whether the geographic and time units are comparable",
        "Whether the map colors are fashionable",
        "Comparisons require attention to changing units and periods.",
      ],
    ],
  },
];

export const secondaryInquiry: SkillContent[] = scopes.map((s) => ({
  id: `g${s.grade}_${s.subject === "Science" ? "science" : "social_studies"}_${s.slug}`,
  name: s.name,
  grade: s.grade,
  subject: s.subject,
  domain: s.domain,
  topic: s.name,
  objective: `Use evidence to reason about ${s.name.toLowerCase()}.`,
  prerequisites: [],
  misconceptions: [],
  strategies: ["evidence_first", "compare_contrast", "guided_questioning"],
  standards: [
    {
      framework: s.subject === "Science" ? "NGSS" : "C3",
      reference: s.reference,
      source:
        s.subject === "Science"
          ? "https://www.nextgenscience.org/overview-topics"
          : "https://www.socialstudies.org/standards/c3",
      alignment: "scope-reference",
    },
  ],
  status: "draft",
  reviewer: null,
  curriculumVersion: "us-secondary-v1",
  provenance:
    "Original Da Vinci practice with US framework scope references, pending educator review. NGSS and C3 use grade bands; this grade placement is a product sequence, not a mandated national sequence. Short items do not replace investigations or extended inquiry.",
  questions: s.cases.map(
    ([scenario, question, answer, distractor, explanation], i) => ({
      role: (["diagnostic", "practice", "mastery"] as const)[i],
      prompt: `${scenario}\n${question}`,
      answer,
      choices: i % 2 ? [distractor, answer] : [answer, distractor],
      hint: s.hint,
      explanation,
      context: s.hint,
      visuals: [{ type: "passage", text: scenario, highlights: [] }],
      responseType: "short",
    }),
  ),
  glossary: {
    evidence:
      "Evidence is an observation, measurement, or source detail relevant to a claim.",
    model: "A model represents selected features of a system and has limits.",
    cause:
      "A cause contributes to an effect through a mechanism; sequence or correlation alone is not enough.",
  },
  rubric: {
    criteria: [
      {
        id: "evidence",
        description: "Use a detail from the scenario.",
        terms: ["evidence", "observation", "source", "data", "model"],
        weight: 1,
      },
      {
        id: "reason",
        description: "Connect evidence to an explanation.",
        terms: ["because", "therefore", "supports", "shows", "means"],
        weight: 1,
      },
    ],
    minScore: 0.75,
    counterEvidence: [],
    sampleExplanation: s.cases[0][4],
  },
}));
